"""Supported NHANES exposure classes."""

NHANES_CLASS_REGISTRY = {
    "PAH": {
        "description": "Urinary polycyclic aromatic hydrocarbon metabolites",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "PAH",
        "chemical_class": "PAH",
        "priority": 10,
    },
    "METALS_BLOOD": {
        "description": "Blood metals",
        "matrix": "blood",
        "requires_creatinine": False,
        "default_file_key": "PBCD",
        "chemical_class": "metal",
        "priority": 20,
    },
    "METALS_URINE": {
        "description": "Urinary metals",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "UM",
        "chemical_class": "metal",
        "priority": 30,
    },
    "COTININE": {
        "description": "Serum cotinine and tobacco smoke exposure markers",
        "matrix": "serum",
        "requires_creatinine": False,
        "default_file_key": "COT",
        "chemical_class": "tobacco_smoke",
        "priority": 5,
    },
    "PFAS": {
        "description": "Serum per- and polyfluoroalkyl substances",
        "matrix": "serum",
        "requires_creatinine": False,
        "default_file_key": "PFAS",
        "chemical_class": "PFAS",
        "priority": 40,
    },
    "PHTHALATES": {
        "description": "Urinary phthalate metabolites",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "PHTHTE",
        "chemical_class": "phthalate",
        "priority": 50,
    },
    "PHENOLS": {
        "description": "Urinary environmental phenols",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "EPHPP",
        "chemical_class": "phenol",
        "priority": 60,
    },
    "VOC_METABOLITES": {
        "description": "Urinary volatile organic compound metabolites",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "UVOC",
        "chemical_class": "VOC_metabolite",
        "priority": 70,
    },
    "VOC_BLOOD": {
        "description": "Blood volatile organic compounds",
        "matrix": "blood",
        "requires_creatinine": False,
        "default_file_key": "VOCWB",
        "chemical_class": "VOC",
        "priority": 80,
    },
    "PESTICIDES_OP": {
        "description": "Urinary organophosphate pesticide metabolites",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "OPD",
        "chemical_class": "pesticide_OP",
        "priority": 90,
    },
    "PESTICIDES_PYRETHROID_HERBICIDE": {
        "description": "Urinary pyrethroid and herbicide metabolites",
        "matrix": "urine",
        "requires_creatinine": True,
        "default_file_key": "UPHOPM",
        "chemical_class": "pesticide_pyrethroid_herbicide",
        "priority": 100,
    },
}
