"""Population simulation package.

Combines the package-native synthetic simulation API with source-compatible
All of Us ingestion, batch execution, phenotype extraction, population
analysis, and validation helpers.
"""

from __future__ import annotations

from . import (
    allofus_adapter,
    batch_runner,
    phenotype_extractor,
    population_analysis,
    validation_framework,
)
from ._core import (
    ALLELE_FREQUENCIES,
    ANCESTRY_DISTRIBUTION,
    CANCER_PHENOTYPES,
    GENOTYPE_CANCER_ORS,
    HAPLOTYPE_BLOCKS,
    GxEAnalysisResult,
    ParticipantRiskSummary,
    PopulationSimulationResult,
    PopulationStats,
    SyntheticParticipant,
    ValidationResult,
    analyze_gxe_interactions,
    compute_population_stats,
    compute_roc_auc,
    generate_synthetic_cancer_labels,
    generate_synthetic_cohort,
    get_cancer_phenotype_definitions,
    run_participant_risk,
    run_population_simulation,
    sample_haplotype_block,
    validate_against_published_ors,
)
from .allofus_adapter import (
    ALLOFUS_PGX_GENES,
    ANCESTRY_MAP,
    BIGQUERY_SQL,
    EXPOSOGRAPH_EXTRA_GENES,
    EXPOSOGRAPH_RELEVANT_GENES,
    PHENOTYPE_ACTIVITY_MAP,
    SURVEY_CONCEPTS,
    build_participant_record,
    derive_gst_from_wgs,
    extract_lifestyle_from_surveys,
    get_bigquery_sql,
    load_all_pgx_files,
    load_ancestry_predictions,
    parse_pgx_tsv,
    pgx_to_exposograph_genotype,
)
from .batch_runner import DEFAULT_CONFIG, PopulationSimulation, run_synthetic_simulation
from .phenotype_extractor import (
    CANCER_PHENOTYPES as EHR_CANCER_PHENOTYPES,
)
from .phenotype_extractor import (
    EXCLUSION_ICD10_PREFIXES,
    PHENOTYPE_SQL,
    SNOMED_MALIGNANT_NEOPLASM,
    build_cancer_labels,
    classify_cancer_from_icd10,
    classify_cancer_from_snomed,
    get_phenotype_sql,
)
from .population_analysis import (
    analyze_genotype_exposure_interactions,
    compute_descriptive_stats,
    compute_risk_distributions,
    generate_population_report,
    load_results,
    stratify_by_ancestry,
)
from .validation_framework import REFERENCE_ORS, compute_calibration, run_full_validation

__all__ = [
    "ALLELE_FREQUENCIES",
    "ALLOFUS_PGX_GENES",
    "ANCESTRY_DISTRIBUTION",
    "ANCESTRY_MAP",
    "BIGQUERY_SQL",
    "CANCER_PHENOTYPES",
    "DEFAULT_CONFIG",
    "EHR_CANCER_PHENOTYPES",
    "EXCLUSION_ICD10_PREFIXES",
    "EXPOSOGRAPH_EXTRA_GENES",
    "EXPOSOGRAPH_RELEVANT_GENES",
    "GENOTYPE_CANCER_ORS",
    "GxEAnalysisResult",
    "HAPLOTYPE_BLOCKS",
    "ParticipantRiskSummary",
    "PHENOTYPE_ACTIVITY_MAP",
    "PHENOTYPE_SQL",
    "PopulationSimulation",
    "PopulationSimulationResult",
    "PopulationStats",
    "REFERENCE_ORS",
    "SNOMED_MALIGNANT_NEOPLASM",
    "SURVEY_CONCEPTS",
    "SyntheticParticipant",
    "ValidationResult",
    "allofus_adapter",
    "analyze_genotype_exposure_interactions",
    "analyze_gxe_interactions",
    "batch_runner",
    "build_cancer_labels",
    "build_participant_record",
    "classify_cancer_from_icd10",
    "classify_cancer_from_snomed",
    "compute_calibration",
    "compute_descriptive_stats",
    "compute_population_stats",
    "compute_risk_distributions",
    "compute_roc_auc",
    "derive_gst_from_wgs",
    "extract_lifestyle_from_surveys",
    "generate_population_report",
    "generate_synthetic_cancer_labels",
    "generate_synthetic_cohort",
    "get_bigquery_sql",
    "get_cancer_phenotype_definitions",
    "get_phenotype_sql",
    "load_all_pgx_files",
    "load_ancestry_predictions",
    "load_results",
    "parse_pgx_tsv",
    "pgx_to_exposograph_genotype",
    "phenotype_extractor",
    "population_analysis",
    "run_full_validation",
    "run_participant_risk",
    "run_population_simulation",
    "run_synthetic_simulation",
    "sample_haplotype_block",
    "stratify_by_ancestry",
    "validate_against_published_ors",
    "validation_framework",
]
